version: "3"

services:
  mongo:
    image: mongo:3.6.6
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./data/mongo/db:/data/db
    environment:
      MONGO_INITDB_DATABASE: onspace_emaildb
  server:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    ports:
      - 5000:5000
      - 3000:3000
    volumes:
      - /app/node_modules
      - /app/client/node_modules
      - ./server:/app
